---
title: 'Tidy Tuesday #2'
author: "Miles Warshauer"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```


```{r libraries}
library(tidyverse)  
library(lubridate)    
library(janitor)       
theme_set(theme_minimal()) 
```

## Tuskegee Airmen Data Work: 

```{r}
airmen <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-08/airmen.csv')
```


```{r, fig.width=18, fig.height=15} 
airmen %>% 
  select(name, state) %>% 
  mutate(region = case_when(
      state %in% c("IN", "In", "IL", "NE", "MN", "OH", "IA", "ND", "SD", "MI", "WI", "KY", "MO", "KS") ~ "Midwest",
      state %in% c("PA", "MD", "DE", "VA", "DC", "WV", "NJ") ~ "Mid-Atlantic",
      state %in% c("NY", "CT", "RI", "VT", "NH", "ME", "MA", "CN") ~ "Northeast",
      state %in% c("AL", "TN", "GA", "FL", "MS", "NC", "SC", "AR", "LA") ~ "Southeast",
      state %in% c("NM", "NV", "AZ", "TX", "OK", "CO", "UT", "CA") ~ "Southwest and California",
      state %in% c("MT", "OR", "WA", "ID") ~ "Northwest",
      state %in% c("Haiti", "HT", "TD", "VI") ~ "Caribbean (International and US Overseas Territories)",
      TRUE ~ "Unknown"
    )
  ) %>% 
  ggplot(aes(x=region))+
  geom_bar(fill="red3", color="gold3")+
  labs(title="Regional Origin Breakdown of Tuskegee Airmen", x="Region", y="Number of Airmen")
```
